name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Lint code
        run: npm run lint
        env:
          CI: true

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Run tests with coverage
        run: npm run test:coverage
        env:
          CI: true

      - name: Check coverage files
        run: |
          echo "Listing coverage directory:"
          ls -la coverage

      - name: Display lcov.info content
        run: |
          echo "Displaying content of lcov.info file:"
          cat coverage/lcov.info || echo "lcov.info not found"

  upload-coverage-report:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload coverage to CodeClimate
        uses: codeclimate/test-reporter-action@v2
        with:
          coverage_command: 'npm run test:coverage'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          CI: true

      - name: Check CodeClimate upload status
        run: echo "Uploading coverage to CodeClimate completed."
